name: myBinder-environment

dependencies:
  - python=3.6
  - biopython=1.70
  - mmtf-python=1.0.9
  - numpy=1.13.3
  - requests=2.18.4
  - sympy=1.1.1
  - nose
  - pyspark
  - py3Dmol
  - py4j
  - python-dateutil
  - ipyleaflet
